server:
  port: 7020
spring:
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  server:
    tomcat:
      max-http-form-post-size: 1000MB
  datasource:
    url: jdbc:mysql://139.159.190.234:3306/word_format?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: work-formatter
    password: Noneplus564925080!
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: com.crane.wordformat.restful.db.JpaPhysicalNamingStrategy
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
decorator:
  datasource:
    p6spy:
      log-format: "\ntime:%(executionTime) || sql:%(sql)\n"


#minio相关配置
minio:
  endpoint: 139.159.190.234
  port: 9000
  accessKey: work-formatter
  secretKey: work-formatter-admin
  bucketName: file


