server:
  port: 7020
spring:
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  server:
    tomcat:
      max-http-form-post-size: 1000MB
