spring:
  datasource:
    url: jdbc:mysql://139.159.190.234:3306/word_format?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: work-formatter
    password: Noneplus564925080!
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: com.crane.wordformat.restful.db.JpaPhysicalNamingStrategy
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
decorator:
  datasource:
    p6spy:
      log-format: "\ntime:%(executionTime) || sql:%(sql)\n"


#minio相关配置
minio:
  endpoint: 139.159.190.234
  port: 9000
  accessKey: work-formatter
  secretKey: work-formatter-admin
  bucketName: file

#打开gzip
server:
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json,application/vnd.openxmlformats-officedocument.wordprocessingml.document,application/octet-stream
    min-response-size: 1024

