spring:
  datasource:
    url: jdbc:mysql://localhost:3306/word_format?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: com.crane.wordformat.restful.db.JpaPhysicalNamingStrategy
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
decorator:
  datasource:
    p6spy:
      log-format: "\ntime:%(executionTime) || sql:%(sql)\n"
